name: weather
description: SmartAvia weather application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
#  collection: ^1.17.0
  equatable: ^2.0.5
  flutter_svg: ^2.0.7
  flutter_dotenv: ^5.1.0
  css_filter: ^1.0.3
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  get_it: ^7.6.4
  dio: ^5.3.3
  json_annotation: ^4.8.1
  either_dart: ^1.0.0
  shared_preferences: ^2.2.1
  rxdart: ^0.27.7
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.2.3
  email_validator: ^2.1.17
  lottie: ^2.6.0
  yandex_mapkit: ^3.3.3
  talker_flutter: ^2.4.3
  talker_dio_logger: ^1.3.0
  talker_bloc_logger: ^1.1.0
  flutter_native_splash: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/weather_icons/
    - google_fonts/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#FF46009C"
  remove_alpha_ios: true
  web:
    generate: false
    image_path: "assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: false
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false
    image_path: "assets/images/logo.png"

flutter_native_splash:
  color: "#46009C"
  fullscreen: true
  android_12:
    image: "assets/images/splash.png"
    icon_background_color: "#46009C"
    fullscreen: true
    color: "#46009C"
  android: true
  ios: true
  web: false